version: '3.5'  

services: 
    backend: 
      build: ../utils/backend-example-docker
      ports: 
        - 8000:8000
      environment:
          - FRONT_URL=http://localhost:5000
          - REDIS=database
    database:
        image: redis
    frontend: 
        build: ../utils/frontend-example-docker
        ports: 
            - 5000:5000
        environment: 
            - API_URL=http://localhost:8000