version: '3.5'  

services: 
    backend: 
      build: ../utils/backend-example-docker
      ports: 
        - 8000:8000
      environment:
          - FRONT_URL=http://localhost:5000
          - DB_USERNAME=example
          - DB_PASSWORD=example
          - DB_NAME=database
          - DB_HOST=db
    db:
      image: postgres
      restart: always
      environment:
        - POSTGRES_USER=example
        - POSTGRES_PASSWORD=example
        - POSTGRES_DB=database

    frontend: 
        build: ../utils/frontend-example-docker
        ports: 
            - 5000:5000
        environment: 
            - API_URL=http://localhost:8000